### ISSUE TITLE
Cannot run openapi in quarkus mode

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#258]
`kamel run API.java --open-api openapi3.yaml -t quarkus.enabled=true` with a simple API, single endpoint.

```
2020-03-11 22:25:54,178 INFO  [org.apa.cam.sup.LRUCacheFactory] (main) Detected and using LURCacheFactory: camel-caffeine-lrucache
2020-03-11 22:25:55,240 INFO  [org.apa.cam.k.cor.qua.RuntimeListenerAdapter] (main) Listener org.apache.camel.k.listener.RuntimeConfigurer@1c33c17b executed in phase Starting
2020-03-11 22:25:55,257 INFO  [org.apa.cam.k.cor.qua.RuntimeListenerAdapter] (main) Listener org.apache.camel.k.listener.PropertiesFunctionsConfigurer@673be18f executed in phase Starting
2020-03-11 22:25:55,273 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Using properties from: file:/etc/camel/conf.d/..2020_03_11_22_25_36.663073311/user.properties,file:/etc/camel/conf.d/user.properties
2020-03-11 22:25:55,312 INFO  [org.apa.cam.k.sup.RuntimeSupport] (main) Looking up loader for language: java
2020-03-11 22:25:55,314 INFO  [org.apa.cam.k.sup.RuntimeSupport] (main) Found loader org.apache.camel.k.loader.java.JavaSourceLoader@64c63c79 for language java from the registry
2020-03-11 22:25:56,644 INFO  [org.apa.cam.k.lis.RoutesConfigurer] (main) Loading routes from: file:/etc/camel/sources/i-source-000/API.java?language=java
2020-03-11 22:25:56,645 INFO  [org.apa.cam.k.sup.RuntimeSupport] (main) Looking up loader for language: xml
2020-03-11 22:25:56,645 INFO  [org.apa.cam.k.sup.RuntimeSupport] (main) Found loader org.apache.camel.k.loader.xml.XmlSourceLoader@27eedb64 for language xml from the registry
2020-03-11 22:25:56,647 INFO  [org.apa.cam.k.lis.RoutesConfigurer] (main) Loading routes from: file:/etc/camel/sources/i-source-001/openapi.xml?language=xml
2020-03-11 22:25:56,647 INFO  [org.apa.cam.k.cor.qua.RuntimeListenerAdapter] (main) Listener org.apache.camel.k.listener.RoutesConfigurer@7c041b41 executed in phase ConfigureRoutes
2020-03-11 22:25:56,673 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) is shutting down
2020-03-11 22:25:56,675 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) uptime 
2020-03-11 22:25:56,676 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) is shutdown in 0.003 seconds
2020-03-11 22:25:56,677 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.apache.camel.quarkus.core.FastCamelContext to org.apache.camel.model.ModelCamelContext
	at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:99)
	at io.quarkus.deployment.steps.Main$start44.deploy_0(Main$start44.zig:78)
	at io.quarkus.deployment.steps.Main$start44.deploy(Main$start44.zig:97)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:218)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.Application.run(Application.java:226)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.ClassCastException: Cannot cast org.apache.camel.quarkus.core.FastCamelContext to org.apache.camel.model.ModelCamelContext
	at java.lang.Class.cast(Unknown Source)
	at org.apache.camel.impl.engine.AbstractCamelContext.adapt(AbstractCamelContext.java:377)
	at org.apache.camel.main.BaseMainSupport.doConfigureCamelContextFromMainConfiguration(BaseMainSupport.java:773)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:531)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:587)
	at org.apache.camel.quarkus.core.CamelMain.postProcessCamelContext(CamelMain.java:59)
	at org.apache.camel.quarkus.core.CamelMain.doStart(CamelMain.java:49)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:121)
	at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:97)
	... 6 more

Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:248)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.Application.run(Application.java:226)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.apache.camel.quarkus.core.FastCamelContext to org.apache.camel.model.ModelCamelContext
	at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:99)
	at io.quarkus.deployment.steps.Main$start44.deploy_0(Main$start44.zig:78)
	at io.quarkus.deployment.steps.Main$start44.deploy(Main$start44.zig:97)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:218)
	... 3 more
Caused by: java.lang.ClassCastException: Cannot cast org.apache.camel.quarkus.core.FastCamelContext to org.apache.camel.model.ModelCamelContext
	at java.lang.Class.cast(Unknown Source)
	at org.apache.camel.impl.engine.AbstractCamelContext.adapt(AbstractCamelContext.java:377)
	at org.apache.camel.main.BaseMainSupport.doConfigureCamelContextFromMainConfiguration(BaseMainSupport.java:773)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:531)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:587)
	at org.apache.camel.quarkus.core.CamelMain.postProcessCamelContext(CamelMain.java:59)
	at org.apache.camel.quarkus.core.CamelMain.doStart(CamelMain.java:49)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:121)
	at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:97)
	... 6 more
```

**Comment by lburgazzoli** [comment]
Depends on:
- [ ] https://github.com/apache/camel-quarkus/issues/877
- [ ] https://github.com/apache/camel/pull/3626

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-k-runtime/pull/318
