### ISSUE TITLE
Re-enable YamlSourceLoaderTest

### ISSUE THREAD

**Issue by orpiske** [apache/camel-k-runtime#687]
This one is having problems with Camel 3.10:

```
[ERROR] Failures: 
[ERROR]   YamlSourceLoaderTest.all:143 Condition failed with Exception:

runtime.loadRoutes('classpath:yaml/routes_all.yaml')
|       |
|       org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Unsupported field: properties
|       	at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:51)
|       	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:172)
|       	at org.apache.camel.k.support.SourcesSupport.loadSources(SourcesSupport.java:75)
|       	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
|       	at org.apache.camel.k.loader.yaml.support.TestRuntime.loadRoutes(TestRuntime.groovy:53)
|       	at org.apache.camel.k.loader.yaml.YamlSourceLoaderTest.all(YamlSourceLoaderTest.groovy:143)
|       Caused by: java.lang.IllegalArgumentException: Unsupported field: properties
|       	at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:248)
|       	at org.apache.camel.dsl.yaml.deserializers.FromDefinitionDeserializer.construct(FromDefinitionDeserializer.java:38)
|       	at org.apache.camel.k.loader.yaml.YamlSourceLoaderDeserializerResolver$FromDeserializer.construct(YamlSourceLoaderDeserializerResolver.java:57)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
|       	at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:74)
|       	at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:32)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
|       	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configure(YamlRoutesBuilderLoader.java:48)
|       	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
|       	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
|       	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
|       	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
|       	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
|       	at org.apache.camel.k.loader.yaml.support.TestRuntime.addRoutes(TestRuntime.groovy:49)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
|       	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
|       	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
|       	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
|       	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
|       	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
|       	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
|       	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
|       	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:170)
|       	... 4 more
<org.apache.camel.k.loader.yaml.support.TestRuntime@29050de5 context=CamelContext(camel-9) builders=[Routes: []] configurations=[]>

[ERROR]   YamlSourceLoaderTest.from with parameters:115 Condition failed with Exception:

runtime.loadRoutes('classpath:yaml/routes_from.yaml')
|       |
|       org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Unsupported field: properties
|       	at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:51)
|       	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:172)
|       	at org.apache.camel.k.support.SourcesSupport.loadSources(SourcesSupport.java:75)
|       	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
|       	at org.apache.camel.k.loader.yaml.support.TestRuntime.loadRoutes(TestRuntime.groovy:53)
|       	at org.apache.camel.k.loader.yaml.YamlSourceLoaderTest.from with parameters(YamlSourceLoaderTest.groovy:115)
|       Caused by: java.lang.IllegalArgumentException: Unsupported field: properties
|       	at org.apache.camel.dsl.yaml.deserializers.OutputAwareFromDefinitionDeserializer.setProperties(OutputAwareFromDefinitionDeserializer.java:87)
|       	at org.apache.camel.dsl.yaml.deserializers.OutputAwareFromDefinitionDeserializer.setProperties(OutputAwareFromDefinitionDeserializer.java:33)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
|       	at org.apache.camel.k.loader.yaml.YamlSourceLoaderDeserializerResolver$RouteFromDeserializer.construct(YamlSourceLoaderDeserializerResolver.java:65)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
|       	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configure(YamlRoutesBuilderLoader.java:48)
|       	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
|       	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
|       	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
|       	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
|       	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
|       	at org.apache.camel.k.loader.yaml.support.TestRuntime.addRoutes(TestRuntime.groovy:49)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
|       	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
|       	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
|       	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
|       	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
|       	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
|       	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
|       	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
|       	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:170)
|       	... 4 more
<org.apache.camel.k.loader.yaml.support.TestRuntime@78d71df1 context=CamelContext(camel-7) builders=[Routes: []] configurations=[]>

[ERROR]   YamlSourceLoaderTest.route with parameters:129 Condition failed with Exception:

runtime.loadRoutes('classpath:yaml/routes.yaml')
|       |
|       org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Unsupported field: properties
|       	at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:51)
|       	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:172)
|       	at org.apache.camel.k.support.SourcesSupport.loadSources(SourcesSupport.java:75)
|       	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
|       	at org.apache.camel.k.loader.yaml.support.TestRuntime.loadRoutes(TestRuntime.groovy:53)
|       	at org.apache.camel.k.loader.yaml.YamlSourceLoaderTest.route with parameters(YamlSourceLoaderTest.groovy:129)
|       Caused by: java.lang.IllegalArgumentException: Unsupported field: properties
|       	at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:248)
|       	at org.apache.camel.dsl.yaml.deserializers.FromDefinitionDeserializer.construct(FromDefinitionDeserializer.java:38)
|       	at org.apache.camel.k.loader.yaml.YamlSourceLoaderDeserializerResolver$FromDeserializer.construct(YamlSourceLoaderDeserializerResolver.java:57)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
|       	at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:74)
|       	at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:32)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
|       	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
|       	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configure(YamlRoutesBuilderLoader.java:48)
|       	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
|       	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
|       	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
|       	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
|       	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
|       	at org.apache.camel.k.loader.yaml.support.TestRuntime.addRoutes(TestRuntime.groovy:49)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
|       	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
|       	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
|       	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
|       	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
|       	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
|       	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
|       	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
|       	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
|       	at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:170)
|       	... 4 more
<org.apache.camel.k.loader.yaml.support.TestRuntime@2eda072 context=CamelContext(camel-8) builders=[Routes: []] configurations=[]>

```

**Comment by orpiske** [comment]
Superseded by #679
